version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/app
    links:
      - mongodb
      - redis
  mongodb:
    image: mongo:4.0.6
    command: mongod --smallfiles
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  redis:
    image: redis:5.0.3
    ports:
      - 6379:6379
